### ISSUE TITLE
Overriding request options

### ISSUE THREAD

**Issue by sancanella** [albinojunior/nodeapi-ts-boilerplate#6]
The default options is always overriding the query options like limit or page
https://github.com/albinojunior/node-crudapi-ts/blob/dac7804be1109e60ab27ee4a5656f8dd7836c3d6/src/common/controllers/crud.ts#L156

**Comment by albinojunior** [comment]
Fixed on [commit](https://github.com/albinojunior/node-crudapi-ts/commit/76c4d7e382836b1ed052d7a5a9e85fa8af5c879f).
