### ISSUE TITLE
UNKNOWN ERROR:  TypeError: filter.execute is not a function

### ISSUE THREAD

**Issue by vuvanbac1997** [albinojunior/nodeapi-ts-boilerplate#8]
ERROR when add field in filter in user model
public filters = ["name"];

UNKNOWN ERROR:  TypeError: filter.execute is not a function
0|node-crudapi-dev  |     at D:\project\NODEJS\node-crudapi-ts\src\common\services\crud.ts:103:24
0|node-crudapi-dev  |     at Array.forEach (<anonymous>)
0|node-crudapi-dev  |     at UserService.processFilters (D:\project\NODEJS\node-crudapi-ts\src\common\services\crud.ts:101:19)
0|node-crudapi-dev  |     at UserService.all (D:\project\NODEJS\node-crudapi-ts\src\common\services\crud.ts:35:30)
0|node-crudapi-dev  |     at index (D:\project\NODEJS\node-crudapi-ts\src\common\controllers\crud.ts:57:54)

**Comment by albinojunior** [comment]
Hey @vuvanbac1997, the filter should be an instance of a Filter class.

See this [file](https://github.com/albinojunior/node-crudapi-ts/blob/master/src/common/filters/search.ts)
