### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by vuvanbac1997** [albinojunior/nodeapi-ts-boilerplate#9]
I see this block of code in **database.ts**.
![image](https://user-images.githubusercontent.com/37699833/102009172-46e15e00-3d68-11eb-907e-443f4522125e.png)
Could you please make an example about sequelize associate between models?

**Comment by albinojunior** [comment]
Hey @vuvanbac1997, you can see more information of sequelize association in the [documentation](https://sequelize.org/v5/manual/associations.html).

**Comment by vuvanbac1997** [comment]
Thank you
